name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署作业同时运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Create .nojekyll file
        run: touch out/.nojekyll
        
      - name: Verify build output
        run: |
          echo "Build output contents:"
          ls -la out/
          echo "CSS files:"
          find out -name "*.css" -type f
          echo "JS files:"
          find out -name "*.js" -type f | head -5
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.4
        with:
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true
